import { Injectable } from '@angular/core';

@Injectable()
export class LinkService {

  constructor() { }

  getlinks() {
    return [
      {
        title: 'CJ',
        subtitle: 'in all his glory',
        listImage: 'assets/placeholder1.jpg',
        listImageAlt: 'just try it',
        image: 'assets/01.jpg',
        imageAlt: '',
        link: 'details/0',
        text: 'CJ\'s best day ever!',
      },
      {
        title: 'Matt',
        subtitle: 'with the do',
        listImage: 'assets/placeholder1.jpg',
        listImageAlt: 'just try it',
        image: 'assets/02.jpg',
        imageAlt: '',
        link: 'details/1',
        text: 'Nice Hair!',
      },
      {
        title: 'Gary',
        subtitle: 'with the do',
        listImage: 'assets/placeholder1.jpg',
        listImageAlt: 'just try it',
        image: 'assets/03.jpg',
        imageAlt: '',
        link: 'details/2',
        text: 'Disco Dance Party at Gary\'s!',
      },
      {
        title: 'Mike',
        subtitle: 'magnets',
        listImage: 'assets/placeholder1.jpg',
        listImageAlt: 'just try it',
        image: 'assets/04.jpg',
        imageAlt: '',
        link: 'details/3',
        text: 'All the magnets!',
      },
      {
        title: 'Pete',
        subtitle: 'foods',
        listImage: 'assets/placeholder1.jpg',
        listImageAlt: 'just try it',
        image: 'assets/05.jpg',
        imageAlt: '',
        link: 'details/4',
        text: 'mmmmmmmmmmm!',
      },
      {
        title: 'RICK',
        subtitle: 'give up already',
        listImage: 'assets/placeholder3.jpg',
        listImageAlt: 'just try it',
        image: 'UH OH',
        imageAlt: 'UH OH',
        link: 'rick',
        text: '',
      },
      {
        title: 'Mike',
        subtitle: 'robots',
        listImage: 'assets/placeholder1.jpg',
        listImageAlt: 'just try it',
        image: 'assets/07.jpg',
        imageAlt: '',
        link: 'details/6',
        text: 'beep beep beep beep',
      },
      {
        title: 'Mike and Brian',
        subtitle: 'beers',
        listImage: 'assets/placeholder1.jpg',
        listImageAlt: 'just try it',
        image: 'assets/08.jpg',
        imageAlt: '',
        link: 'details/7',
        text: 'Cheers!',
      },
      {
        title: 'Brian',
        subtitle: 'ice cream',
        listImage: 'assets/placeholder1.jpg',
        listImageAlt: 'just try it',
        image: 'assets/09.jpg',
        imageAlt: '',
        link: 'details/8',
        text: 'YUUUUMMMMMMMM!',
      },
      {
        title: 'Matt and Andrew',
        subtitle: 'Co-Ops',
        listImage: 'assets/placeholder1.jpg',
        listImageAlt: 'just try it',
        image: 'assets/10.jpg',
        imageAlt: '',
        link: 'details/9',
        text: 'All aboard!!',
      },
      {
        title: 'Mike',
        subtitle: 'gokarts',
        listImage: 'assets/placeholder1.jpg',
        listImageAlt: 'just try it',
        image: 'assets/11.jpg',
        imageAlt: '',
        link: 'details/10',
        text: 'Vroooooom!!',
      },
      {
        title: 'Kurt',
        subtitle: 'old man',
        listImage: 'assets/placeholder1.jpg',
        listImageAlt: 'just try it',
        image: 'assets/12.jpg',
        imageAlt: '',
        link: 'details/11',
        text: 'I\ve fallen and I can\'t get up!!',
      },
      {
        title: 'Shawn',
        subtitle: 'aka RED',
        listImage: 'assets/placeholder1.jpg',
        listImageAlt: 'just try it',
        image: 'assets/13.jpg',
        imageAlt: '',
        link: 'details/12',
        text: 'This your brain trying to comprehend your own stupidity. ~RED',
      },
      {
        title: 'Greg, Rick, Pete and Bob',
        subtitle: 'the wiggles',
        listImage: 'assets/placeholder1.jpg',
        listImageAlt: 'just try it',
        image: 'assets/14.jpg',
        imageAlt: '',
        link: 'details/13',
        text: 'what a performance!',
      },
      {
        title: 'Contact Me',
        subtitle: 'give up already',
        listImage: 'assets/qr-contact.jpg',
        listImageAlt: 'just try it',
        image: 'UH OH',
        imageAlt: 'UH OH',
        link: 'contact',
        text: '',
      },
      // {
      //   title: 'Table Flip',
      //   subtitle: 'THAT\'s IT',
      //   listImage: 'assets/placeholder1.jpg',
      //   listImageAlt: 'just try it',
      //   image: 'assets/16.gif',
      //   imageAlt: '',
      //   link: 'details/15',
      //   text: 'I\M OUT!',
      // },
    ];
  }

}
